#! /bin/bash

readonly USAGE="Automated version management and release publishing (in bash).

Usage:
  gitate [command]

Available Commands:
  create          Create a new version of your app.
  delete          Delete a tag.
  version         Show version.

Flags:
  -h, --help      Show this help.
  -d, --dry-run   Dry run. Skip tag creation, show version and release notes."

readonly SEMANTIC_RELEASE_VERSION="0.1.0"
readonly ERROR_ARGUMENTS=2

options() {
        while :; do
                case $1 in
                        create)
                                echo "Comenzando..."
                                ;;
                        delete)
                                echo "Eliminando..."
                                ;;
                        version)
                                echo "Semantic-release: v${SEMANTIC_RELEASE_VERSION}"
                                ;;
                        -h|-\?|--help)
                                echo "$USAGE"
                                exit
                                ;;
                        -d|--dry-run)
                                dry_run=1
                                ;;
                        -?*)
                                echo "Unknown option: $1" >&2
                                echo "$USAGE"
                                exit "$ERROR_ARGUMENTS"
                                ;;
                        ?*)
                                echo "Unknown argument: $1" >&2
                                echo "$USAGE"
                                exit "$ERROR_ARGUMENTS"
                                ;;
                        "")
                                if [[ -z "$1" ]]; then
                                        echo "$USAGE"
                                fi
                                break
                                ;;
                esac
                shift
        done


}

options "$@"
